### ISSUE TITLE
Scroll não funciona?

### ISSUE THREAD

**Issue by lamecksilva** [httpiago/sample-react-and-next-app#1]
#### Primeiramente parabéns mano, gostei do seu web app, gostei mais da parte com Next.JS... enfim... 

Quando eu vou lá no app e coloco meu username (por exemplo), ele lista os repos mas ele não "scrolla", acredito que a altura da pagina é fixa e não dinâmica (para se adequar a quantos repo o username tenha), vou colocar uma foto aqui em baixo. Mas novamente, está muito boa sua aplicação.

### Teste com Airbnb
![image](https://user-images.githubusercontent.com/31391753/52482819-0d9a9e80-2b91-11e9-969d-12aadc3eb934.png)

**Comment by iagobruno** [comment]
😁 obrigado @lamecksilva !
Então, esse foi meu primeiro projeto usando o React e na época eu só tinha o básico de flexbox e acabei deixando passar esse problema.

**Comment by lamecksilva** [comment]
Nah, tranquilo mano... Sei muito bem como que deixamos as coisas passar nos primeiros projetos, principalmente com o ReactJS
